name = "apdf417"
main = "worker/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./web/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "apdf147"
database_id = "9f7768ee-1430-46ec-b1de-a10b07d6795e"
